<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_vehicle">
    <!-- VEHICLE DIMENSIONS -->
    <xacro:property name="vehicle_length" value="2.0" />
    <xacro:property name="vehicle_width" value="1.0" />
    <xacro:property name="vehicle_height" value="0.3" />
    <xacro:property name="ground_clearance" value="0.025" />

    <!-- WHEEL SETUP -->
    <xacro:property name="wheel_diameter" value="0.13" />
    <xacro:property name="wheel_width" value="0.05" />

    <xacro:property name="wheel_0_origin_x" value="0.0" />
    <xacro:property name="wheel_0_origin_y" value="${0.3 * vehicle_width}" />
    <xacro:property name="wheel_0_origin_z" value="${-(ground_clearance + vehicle_height / 2 - wheel_diameter / 2)}" />

    <xacro:property name="wheel_1_origin_x" value="0.0" />
    <xacro:property name="wheel_1_origin_y" value="${-0.3 * vehicle_width}" />
    <xacro:property name="wheel_1_origin_z" value="${-(ground_clearance + vehicle_height / 2 - wheel_diameter / 2)}" />

    <xacro:property name="roller_0_origin_x" value="${0.4 * vehicle_length}" />
    <xacro:property name="roller_0_origin_y" value="0.0" />
    <xacro:property name="roller_0_origin_z" value="${-(ground_clearance + vehicle_height / 2 - wheel_diameter / 2)}" />

    <xacro:property name="roller_1_origin_x" value="${-0.4 * vehicle_length}" />
    <xacro:property name="roller_1_origin_y" value="0.0" />
    <xacro:property name="roller_1_origin_z" value="${-(ground_clearance + vehicle_height / 2 - wheel_diameter / 2)}" />

    <!-- SENSOR SETUP -->
    <xacro:property name="scanner_0_origin_x" value="${0.5 * vehicle_length}" />
    <xacro:property name="scanner_0_origin_y" value="${0.5 * vehicle_width}" />
    <xacro:property name="scanner_0_origin_z" value="0.0" />

    <xacro:property name="scanner_1_origin_x" value="${-0.5 * vehicle_length}" />
    <xacro:property name="scanner_1_origin_y" value="${-0.5 * vehicle_width}" />
    <xacro:property name="scanner_1_origin_z" value="0.0" />

    <!-- GAZEBO INCLUDE -->
    <xacro:include filename="$(find diff_description)/urdf/main.gazebo.xacro" />

    <!-- COMMON INCLUDES -->
    <xacro:include filename="$(find common_description)/urdf/colors.xacro" />
    <xacro:include filename="$(find common_description)/urdf/constants.xacro" />
    <xacro:include filename="$(find common_description)/urdf/driven_wheel.urdf.xacro" />
    <xacro:include filename="$(find common_description)/urdf/free_wheel.urdf.xacro" />
    <xacro:include filename="$(find common_description)/urdf/sensors/sick_nanoscan3.urdf.xacro" />
    <xacro:include filename="$(find common_description)/urdf/sensors/unknown_imu.urdf.xacro" />
    
    <!-- SD VEHICLE INCLUDES -->
    <xacro:include filename="$(find diff_description)/urdf/base.urdf.xacro" />

    <!-- BASE -->
    <xacro:base_setup />

    <!-- DRIVEN WHEELS -->
    <xacro:driven_wheel name="left_wheel" parent="base_link">
        <origin xyz="${wheel_0_origin_x} ${wheel_0_origin_y} ${wheel_0_origin_z}" rpy="${M_PI / 2} ${M_PI / 2} ${M_PI}" />
    </xacro:driven_wheel>

    <xacro:driven_wheel name="right_wheel" parent="base_link">
        <origin xyz="${wheel_1_origin_x} ${wheel_1_origin_y} ${wheel_1_origin_z}" rpy="${M_PI / 2} ${M_PI / 2} ${M_PI}" />
    </xacro:driven_wheel>

    <!-- FREE WHEELS -->
    <xacro:free_wheel name="front_roller" parent="base_link">
        <origin xyz="${roller_0_origin_x} ${roller_0_origin_y} ${roller_0_origin_z}" rpy="0.0 0.0 0.0" />
    </xacro:free_wheel>

    <xacro:free_wheel name="rear_roller" parent="base_link">
        <origin xyz="${roller_1_origin_x} ${roller_1_origin_y} ${roller_1_origin_z}" rpy="0.0 0.0 0.0" />
    </xacro:free_wheel>

    <!-- SENSORS -->
    <xacro:sick_nanoscan3 name="front_scanner" parent="base_link" ros_topic="scan_front">
        <origin xyz="${scanner_0_origin_x} ${scanner_0_origin_y} ${scanner_0_origin_z}" rpy="0.0 0.0 ${-0.5 * M_PI}"/>
    </xacro:sick_nanoscan3>
    
    <xacro:sick_nanoscan3 name="rear_scanner" parent="base_link" ros_topic="scan_rear">
        <origin xyz="${scanner_1_origin_x} ${scanner_1_origin_y} ${scanner_1_origin_z}" rpy="0.0 0.0 ${0.5 * M_PI}"/>
    </xacro:sick_nanoscan3>

    <xacro:unknown_imu name="imu" parent="base_link" ros_topic="imu">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:unknown_imu>

</robot>

