<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="free_wheel" params="name parent *origin">
        <link name="${name}_link">
            <inertial>
                <mass value="0.001" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <!--mesh filename="file:///$(find pia-description)/meshes/mecanum_wheel_right.stl" scale="0.001 0.001 0.001"/-->
                    <sphere radius="${wheel_diameter / 2}" />
                </geometry>
                <material name="red" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="${wheel_diameter / 2}" />
                </geometry>
            </collision>
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}_link"/>
            <xacro:insert_block name="origin" />
        </joint>
    </xacro:macro>
</robot>