<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="sd_wheel" params="name parent *origin">
        <!-- STEERING -->
        <link name="${name}_steer_link">
            <inertial>
                <mass value="0.001" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
            </inertial>

            <!--visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file:///$(find pia-description)/meshes/mecanum_wheel_right.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="red" />
            </visual-->

            <!--collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.0 0.0 0.0"/>
                </geometry>
            </collision-->
        </link>

        <joint name="${name}_steer_joint" type="revolute">
            <parent link="${parent}"/>
            <child link="${name}_steer_link"/>
            <xacro:insert_block name="origin" />
            <axis xyz="0 0 1" />
            <limit lower="0" upper="${2 * M_PI}" 
                   effort="30" velocity="${2 * M_PI}" />
        </joint>


        <!-- DRIVING -->
        <link name="${name}_drive_link">
            <inertial>
                <mass value="0.001" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
            </inertial>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <!--mesh filename="file:///$(find pia-description)/meshes/mecanum_wheel_right.stl" scale="0.001 0.001 0.001"/-->
                    <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}" />
                </geometry>
                <material name="red" />
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}" />
                </geometry>
            </collision>
        </link>

        <joint name="${name}_drive_joint" type="continuous">
            <parent link="${name}_steer_link"/>
            <child link="${name}_drive_link"/>
            <origin xyz="0.0 0.0 0.0" rpy="${M_PI / 2} ${M_PI / 2} 0.0" />
            <axis xyz="0 0 1" />
        </joint>
    </xacro:macro>
</robot>