<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--xacro:macro name="base_setup" params="vehicle_length vehicle_width vehicle_height ground_clearance"-->
    <xacro:macro name="base_setup">
        <link name="base_footprint" />

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0.0 0.0 ${vehicle_height / 2 + ground_clearance}" rpy="0.0 0.0 0.0" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz="0.0 0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <!--mesh filename="package://turtlebot3_description/meshes/bases/burger_base.stl" scale="0.001 0.001 0.001"/-->
                    <box size="${vehicle_length} ${vehicle_width} ${vehicle_height}" />
                </geometry>
                <material name="white" />
            </visual>

            <!--collision>
                <origin xyz="0.0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${vehicle_length} ${vehicle_width} ${vehicle_height}" />
                </geometry>
            </collision-->

            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="8.2573504e-01" />
                <inertia ixx="2.2124416e-03" ixy="-1.2294101e-05" ixz="3.4938785e-05"
                         iyy="2.1193702e-03" iyz="-5.0120904e-06"
                         izz="2.0064271e-03" />
            </inertial>
        </link>
    </xacro:macro>
</robot>